title: 中国RISC-V用户组
description: China RISC-V User Group
show_downloads: false
google_analytics:
theme: 
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
