title: CNRV
description: 中国RISC-V用户组
show_downloads: false
google_analytics: UA-102898438-1
theme: 
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
